### ISSUE TITLE
pyproject.toml error

### ISSUE THREAD

**Issue by Temmie45** [PWhiddy/PokemonRedExperiments#10]
I'm having issues installing the requirements. I'm trying to get this going on windows 10 but I keep getting this error.

 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup C:\Users\Taylor\AppData\Local\Temp\pip-install-ywd_jsyp\contourpy_234d85d7ae30461d8bba25ed36f0cad5 C:\Users\Taylor\AppData\Local\Temp\pip-install-ywd_jsyp\contourpy_234d85d7ae30461d8bba25ed36f0cad5\.mesonpy-b5w3yq6i -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\Taylor\AppData\Local\Temp\pip-install-ywd_jsyp\contourpy_234d85d7ae30461d8bba25ed36f0cad5\.mesonpy-b5w3yq6i\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.2
      Source dir: C:\Users\Taylor\AppData\Local\Temp\pip-install-ywd_jsyp\contourpy_234d85d7ae30461d8bba25ed36f0cad5
      Build dir: C:\Users\Taylor\AppData\Local\Temp\pip-install-ywd_jsyp\contourpy_234d85d7ae30461d8bba25ed36f0cad5\.mesonpy-b5w3yq6i
      Build type: native build
      Project name: contourpy
      Project version: 1.1.0

      ..\meson.build:1:0: ERROR: Could not parse vswhere.exe output

      A full log can be found at C:\Users\Taylor\AppData\Local\Temp\pip-install-ywd_jsyp\contourpy_234d85d7ae30461d8bba25ed36f0cad5\.mesonpy-b5w3yq6i\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Is there something I'm missing or doing wrong?

**Comment by PWhiddy** [comment]
Hey! I did some research online and it looks like it might be using 32 bit python instead of 64 bit?

https://www.reddit.com/r/learnpython/comments/15n9jcb/error_when_installing_matplotlib_via_pip/

So perhaps upgrading your python version might this this.

**Comment by Temmie45** [comment]
I did a fresh install with the 3.12 64 bit installer. Still getting the same thing.

**Comment by PWhiddy** [comment]
Hm. It's possible that 3.12 could be so new that its also causing it to try to build that package from source. 3.10 is what I have tested it. Conda may also helpful for managing versions/environments!

**Comment by Temmie45** [comment]
I'll try a 3.10 install

**Comment by Temmie45** [comment]
Sorry if I'm being annoying. How do I get it to use the 3.10 version if I have both 3.10 and 3.12 installed?

**Comment by PWhiddy** [comment]
I have not tried this on windows myself but looks like you might be able to do something like `py -3.10 ...`

Based on the article
https://martinfritz.medium.com/work-with-multiple-versions-of-python-on-windows-10-eed1e5f52f07

**Comment by Temmie45** [comment]
It does indeed need 3.10 so be aware of that I suppose

**Comment by PWhiddy** [comment]
Good to know! So that worked for you?

**Comment by Temmie45** [comment]
I was also apparently missing some build tools and those are installing right now. But 3.10 got rid of the original error

**Comment by Temmie45** [comment]
And that's a successful build. One last question just for curiosity. Are the forks AI that others trained?

**Comment by PWhiddy** [comment]
The forks are copies of this repository that others have made so that they can save/track modifications they make. People may upload their own trained versions to these but I am not aware of anyone having done that just yet.
