### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.4.14

### ISSUE THREAD

**Issue by nathanjace** [PWhiddy/PokemonRedExperiments#108]
I tried to modify the requirements.txt to match the latest version of jaxlib (0.4.19), but with no avail. I tried to manually install version 0.4.14 but it's not offered anymore.
Does anyone know what I should do?

P.S. I'm on MacOS, with the latest version of python installed, homebrew and ffmpeg.

**Comment by PWhiddy** [comment]
Many of the dependencies could be updated, but everything needs to be tested after doing so. Hope you were able to get it working!
