### ISSUE TITLE
RuntimeError: Program 'ffmpeg' is not found; perhaps install ffmpeg using 'apt-get install ffmpeg'.

### ISSUE THREAD

**Issue by susssssssssssss** [PWhiddy/PokemonRedExperiments#11]
When i run the python file, "run_pretrained_interactive.py" i get the error RuntimeError: Program 'ffmpeg' is not found; perhaps install ffmpeg using 'apt-get install ffmpeg'. can someone tell me what this means and how to fix it?

**Comment by Luk-ESC** [comment]
You need to install ffmpeg

**Comment by ekramzafar** [comment]
The error message you are getting means that FFmpeg is not installed on your system, or it is not recognized by the Python script. To fix this, you need to install FFmpeg on your Windows PC and add it to your system path. Here are the steps to do that:

Download the zip file of the latest version of FFmpeg from here.
Extract the zip file using a file archiver such as 7-Zip or WinRAR.
Rename the extracted folder to FFmpeg and move it to the root of your C: drive.
Open Command Prompt as an administrator and run the following command: setx /m PATH "C:\ffmpeg\bin;%PATH%"
Restart your computer and verify the installation by running: ffmpeg -version in Command Prompt.

**Comment by susssssssssssss** [comment]
Thank you i just had to restart my pc
