### ISSUE TITLE
Algorithms used?

### ISSUE THREAD

**Issue by DiAvisoo** [PWhiddy/PokemonRedExperiments#110]
Love this project!

Mind adding a section in the README about what algorithms used to get a quick overview of how this works?
I'm gonna look at the code but would be very convensient to get some info about this.

**Comment by PWhiddy** [comment]
Hi! 
Yes that would be great to have in the readme. Hoping to add this as well as some standard baseline results tables in the not so far future.
For now, short answer is that it uses PPO with fairly normal hyperparameters. 
You can see these here:
https://github.com/PWhiddy/PokemonRedExperiments/blob/624e6f08d284a498d56e073e4434cd8053fab9a3/baselines/run_baseline_parallel_fast.py#L62

Rewards are a bit more complicated, video describes some of this but you'll have to look at the code for more details for now.
