### ISSUE TITLE
IndexError: index 39 is out of bounds for axis 0 with size 8

### ISSUE THREAD

**Issue by antogenny91** [PWhiddy/PokemonRedExperiments#116]
Hi there! 
First of all: thanks for the opportunity to play with AI!

I got an issue after install everything as define in the video and readme file. 
Unfortunately, I received an IndexError, aka out of bounds error, for axis 0 with size 8 when I run the "run_pretrained_interactive.py" file. Screenshot in attachment.
I've tried to change some values on "red_gym_env" file for col_steps parameter, with no luck.

Did you get this kind of issue before? Could you please help me to solve it?

Waiting your kindly response, thanks a lot and best regards.
 
![Error](https://github.com/PWhiddy/PokemonRedExperiments/assets/20660526/e8900632-fb19-40d4-84ab-072af5816563)

**Comment by LockdownMadness** [comment]
I have the same issue, also just want to say thanks also as this is amazing and love the work!!!

**Comment by PWhiddy** [comment]
Sorry I pushed a bad commit yesterday. Should be fixed now!
