### ISSUE TITLE
cant install torch

### ISSUE THREAD

**Issue by Milanorxd** [PWhiddy/PokemonRedExperiments#133]
when i try to run the py code run_pretrained_interactive.py, on a2c.py for some reason it cant import torch and I tried different ways to install it such as using pip (ERROR: Could not find a version that satisfies the requirement torch (from versions: none) / ERROR: No matching distribution found for torch) and downloading directly from pytorch github (doesn´t work for some reason). I´m stuck at this problem and i feel that i am super close to actually running this thing. BTW i´m using a macbook pro m1, if that helps at all.
<img width="857" alt="Screen Shot 2023-11-02 at 18 34 18" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/afea1503-eb07-4879-b83b-ebc6af0519fc">
<img width="652" alt="Screen Shot 2023-11-02 at 18 37 24" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/569020ab-17c7-45a5-9cb1-102480feb4a3">

**Comment by PWhiddy** [comment]
Try running `pip3 install -r requirements.txt` and let me know how that goes.

**Comment by Milanorxd** [comment]
> Try running `pip3 install -r requirements.txt` and let me know how that goes.

I run it before the problem I had and for some reason it went without problems, now this appears:
<img width="834" alt="Screen Shot 2023-11-02 at 18 55 12" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/4d784967-a8bc-4159-b29a-b7464ece2a02">
<img width="832" alt="Screen Shot 2023-11-02 at 18 55 32" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/a635ce38-0a18-40f7-bf5f-d43029919a2e">

**Comment by PWhiddy** [comment]
Is there more output above that error?

**Comment by Milanorxd** [comment]
> Is there more output above that error?

now that I remember correctly I also had trouble while trying to install the requirements, stable_baselines3 had problems with torch i think , i literally had troubles almost every step of the way lol, the emulator was a pain to install now this,
<img width="789" alt="Screen Shot 2023-11-02 at 19 22 19" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/ad6f5fac-a271-4cf0-9006-91e3ddc884be">

**Comment by PWhiddy** [comment]
For the pretrained model to model to work, you need specific versions of certain packages, so I don’t recommend trying to individually install the latest version by doing “pip install X”. Please make sure you’re using python 3.10 or 11, and try the pip3 install -r requirements.txt. If possible a clean venv or conda env may help too.

**Comment by Milanorxd** [comment]
> For the pretrained model to model to work, you need specific versions of certain packages, so I don’t recommend trying to individually install the latest version by doing “pip install X”. Please make sure you’re using python 3.10 or 11, and try the pip3 install -r requirements.txt. If possible a clean venv or conda env may help too.

so I downgraded to python3.11 and installed the requirements, I tried to run the run_pretrained_interactive.py and this happened.
<img width="784" alt="Screen Shot 2023-11-02 at 19 49 57" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/bb0a0349-48a3-4311-8642-4fef11901000">

**Comment by PWhiddy** [comment]
do you have homebrew? if so you can install it with `brew install ffmpeg`. If not you can look up how to install ffmpeg and add it to path on macos.

**Comment by Milanorxd** [comment]
> nice! do you have homebrew? if so you can install it with `brew install ffmpeg`. If not you can look up how to install ffmpeg and add it to path on macos.

TYSM! I finally was able to do it after installing homebrew and instaling ffmpeg 
<img width="469" alt="Screen Shot 2023-11-02 at 20 13 37" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/149727114/243af2f2-2924-4c75-9d71-a0a53c31d612">

**Comment by PWhiddy** [comment]
yay! glad :)
