### ISSUE TITLE
Using GPU on Windows

### ISSUE THREAD

**Issue by NinjaDev06** [PWhiddy/PokemonRedExperiments#136]
Hi, I'm new to this project and it's amazing!

I'm using Windows and I just built a good gaming PC so I would like to use it for training my experimentation on this project. I managed to make the training run but I see this message `Using cpu device`.

Do someone has some tips to help me found how to use my AMD RX 7800 XT?
I looked for using Docker, but I don't find the configuration for AMD drivers.

**Comment by PWhiddy** [comment]
Hey! Unfortunately amd gpu's don't have great support in most ML libraries. If you can get rocm to work with pytorch, then you might be able to run this on your gpu, but I can't make any guarantees.

**Comment by Iron-Bound** [comment]
I'm running Linux with a 7900xtx, rocm is annoying if you have to compile it, so this pre configured container helps a bunch https://hub.docker.com/r/rocm/pytorch

**Comment by PWhiddy** [comment]
Oh @Iron-Bound you've been successfully running this with amd gpu?

**Comment by NinjaDev06** [comment]
Thank @Iron-Bound! I will try that.

**Comment by Iron-Bound** [comment]
I didn't pay the Nvidia tax, so all my training sessions are on and.

**Comment by NinjaDev06** [comment]
@Iron-Bound are you using rocm/pytorch Docker Image from a Windows or Linux OS?

I think the command is only compatible for Linux because I received that error when I run it.
`docker: Error response from daemon: error gathering device information while adding custom device "/dev/kfd": no such file or directory.`

I tried to convert it for Windows, but without success.

**Comment by Iron-Bound** [comment]
Linux would be best, can you try to pass the GPU via docker+WSL or podman machine?
