### ISSUE TITLE
remove jaxlib version in requirements.txt

### ISSUE THREAD

**Issue by HughMungis** [PWhiddy/PokemonRedExperiments#137]
current error message is this
`Downloading https://www.piwheels.org/simple/jax-jumpy/jax_jumpy-1.0.0-py3-none-any.whl (20 kB)
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.14
ERROR: No matching distribution found for jaxlib==0.4.14
`

**Comment by PWhiddy** [comment]
Hey! I think I saw in another issue someone having the same problem. Curious, if you upgrade the jaxlib version in the `requirements.txt` does it fix the issue? If so we can update this in the repository.

**Comment by HughMungis** [comment]
> Hey! I think I saw in another issue someone having the same problem. Curious, if you upgrade the jaxlib version in the `requirements.txt` does it fix the issue? If so we can update this in the repository.

yeah. In requirements.txt i just took out the `==0.4.14` in front of jaxlib and it works now. recommend that change
