### ISSUE TITLE
Feature Request: Useful Interrupt

### ISSUE THREAD

**Issue by HughMungis** [PWhiddy/PokemonRedExperiments#139]
So I'd like to stop my run manually but I don't want to lose the data. Is it possible to add an interrupt (Ctrl - L or whatever) so that the run ends, but the data isn't lost?

**Comment by PWhiddy** [comment]
Hi! All run data is written to files as well as model checkpoints, so if a run terminates you can restart where you left off. Change the `file_name` variable in the training script to point to the checkpoint you want to start from.
