### ISSUE TITLE
Error: CPU is stuck

### ISSUE THREAD

**Issue by speedyconzales** [PWhiddy/PokemonRedExperiments#14]
when launching the `run_pretrained_interactive.py` 

I will get the following:
- window with pyboy is opening 
- terminal output:
```2023-10-16 01:24:12.404 Python[9018:3337803] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
step:     16 event:  0.00 level:  0.00 heal:  0.00 op_lvl:  0.00 dead: -0.00 badge:  0.00 explore:  0.00 sum:  0.004116     pyboy.core.cpu                 ERROR    CPU is stuck: 
A: 72, F: 10, B: 00, C: BA, D: 00, E: 04, HL: C0C0, SP: C0E4, PC: 801A ()
Opcode: []  Interrupts - IME: False, IE: 00001101, IF: 00010000
LCD Intr.: 62, LY:102, LYC:0
Timer Intr.: 65536
halted:False, interrupt_queued:False, stopped:False
```

I installed python version 3.10.13
I am on an M1 Macbook

**Comment by dukemagus** [comment]
this is a pyboy error rather than a experiment error. you can open an issue on pyboy's repo:

https://github.com/Baekalfen/PyBoy/blob/a464e6949a0681eeda34d3c4d476db19b42aced1/pyboy/core/cpu.py#L134

[according to this guy](https://raphaelstaebler.medium.com/building-a-gameboy-from-scratch-part-2-the-cpu-d6986a5c6c74) PC is a process counter register on the gameboy processor, it increments with each CPU cycle. It may be a good starting place to check, too

**Comment by speedyconzales** [comment]
> this is a pyboy error rather than a experiment error. you can open an issue on pyboy's repo:
> 
> https://github.com/Baekalfen/PyBoy/blob/a464e6949a0681eeda34d3c4d476db19b42aced1/pyboy/core/cpu.py#L134
> 
> [according to this guy](https://raphaelstaebler.medium.com/building-a-gameboy-from-scratch-part-2-the-cpu-d6986a5c6c74) PC is a process counter register on the gameboy processor, it increments with each CPU cycle. It may be a good starting place to check, too

thanks for the hints. pyboy itself is running the rom just fine.
actually this error was caused by using the wrong rom. you need to make sure to use the rom with the right sha1 sum (the USA language version instead of any other language version of the rom)

**Comment by PWhiddy** [comment]
Oh interesting, good catch! I wish it worked with other versions too.
