### ISSUE TITLE
ValueError in map_frame_writer v2-env

### ISSUE THREAD

**Issue by Death-Strike-Gaming** [PWhiddy/PokemonRedExperiments#141]
Mismatched dimensions in red_gym_env_v2.py.

env_config from baseline_fast_v2
{
                'headless': False, 'save_final_state': True, 'early_stop': False,
                'action_freq': 24, 'init_state': '../init.state', 'max_steps': ep_length, 
                'print_rewards': True, 'save_video': True, 'fast_video': True, 'session_path': sess_path,
                'gb_path': '../PokemonRed.gb', 'debug': False, 'reward_scale': 0.5, 'explore_weight': 2
}

### Description

red_gym_env_v2 attempts to add an image to the video using `map_frame_writer.add_image`, a ValueError is raised due to a mismatch between the image dimensions and the initialized video dimensions.

### Steps to Reproduce

1. Initialize the `map_frame_writer` with a video size of (24, 24).
2. Attempt to add an image with dimensions (48, 48) using the `add_video_frame` method.
3. Observed ValueError indicating the dimension mismatch.

###Resulting Behavior

The script terminates with the following ValueError:
ValueError: Image dimensions (48, 48) do not match those of the initialized video (24, 24).

This also leads to a `BrokenPipeError` and `EOFError` in a multiprocessing environment, as the subprocess handling the frame writing is terminated unexpectedly.

### Environment

- Operating System: [e.g., Windows 10]
- Python Version: [e.g., Python 3.10]
- Library Version: [e.g., mediapy X.X.X, stable_baselines3 X.X.X]

### Additional Context

This issue causes the reinforcement learning training loop to crash, preventing any further training progress.

**Comment by PWhiddy** [comment]
fixed :)
