### ISSUE TITLE
Where do the models originate? (question)

### ISSUE THREAD

**Issue by ethicalhacker7192** [PWhiddy/PokemonRedExperiments#149]
Hi, I was looking and trying out your code and I was wondering where your models came from, I am very curious how you got pyboy working together with gym as well.

**Comment by PWhiddy** [comment]
Hi! The model in the base version is the default CNN from stablebaselines (NatureCNN). As for how pyboy and gym are working together, see this file
https://github.com/PWhiddy/PokemonRedExperiments/blob/master/baselines/red_gym_env.py

**Comment by ethicalhacker7192** [comment]
just as a tip in github instead of doing a new line and doing your link, do [yoursubject] (yourlink) of course without the space.
