### ISSUE TITLE
does not work with windows

### ISSUE THREAD

**Issue by tails2012timnew** [PWhiddy/PokemonRedExperiments#154]
I'm super upset about this...
so I'm never using things from this dev again.

**Comment by PWhiddy** [comment]
It works fine on windows! Just a bit more work to set up. Check out one of the other related issues or hop into the discord for help. Good luck!

**Comment by tails2012timnew** [comment]
okay! thanks for the help! :)

**Comment by tails1154** [comment]
this is so cringy looking back at this "IM NEVER USING THSI FROM THSI DEV AGAIN"111!!!!111! omg im so immature then
