### ISSUE TITLE
create_exploration_memory() is hard to understand.

### ISSUE THREAD

**Issue by Garbage123King** [PWhiddy/PokemonRedExperiments#156]
I find it shows level, hp, explore as bar. But what about color, cover, bound.
I notice hp is green bar. But I didn't find where define green.
And when I scale up pixels, bars actually are blurry.
![dfesr353r](https://github.com/PWhiddy/PokemonRedExperiments/assets/70872685/b911a539-2377-4f71-bf58-81299265304a)

**Comment by PWhiddy** [comment]
Its definitely not standard or easy to understand. It can be removed without much impact on performance too. Was working on that in a branch but didn't full match original performance. 
you can also check out this repo which has a simpler implementation:
https://github.com/PufferAI/pokegym
