### ISSUE TITLE
Can't get anything running on Windows.

### ISSUE THREAD

**Issue by setomage** [PWhiddy/PokemonRedExperiments#16]
I downloaded the files, and have the game in the folder PokemonRedExperiments-master folder, but bring up a python window and trying to run anything always gives me 'invalid syntax" what am I missing?

**Comment by alexkrolak** [comment]
> I downloaded the files, and have the game in the folder PokemonRedExperiments-master folder, but bring up a python window and trying to run anything always gives me 'invalid syntax" what am I missing?

There were many hurdles to getting this running on Windows for me. It took a few hours of googling to finally get it to just run, but it is doable. I needed to download/install Anaconda, then conda install certain dependencies, then more or less trial and error/googling issues before the "python run_retrained_interactive.py" command worked.

**Comment by setomage** [comment]
Will try everything when I get home from work. Thanks for letting me know.

**Comment by speedyconzales** [comment]
> > I downloaded the files, and have the game in the folder PokemonRedExperiments-master folder, but bring up a python window and trying to run anything always gives me 'invalid syntax" what am I missing?
> 
> There were many hurdles to getting this running on Windows for me. It took a few hours of googling to finally get it to just run, but it is doable. I needed to download/install Anaconda, then conda install certain dependencies, then more or less trial and error/googling issues before the "python run_retrained_interactive.py" command worked.

None of the mentioned tools [Anaconda, conda] are mandatory to run this. I recommend you should look into python and virtual environments for a better understanding.
Instead of installing these tools you could have just made a virtual environment and installed all the dependencies of requirements.txt with pip inside the virtual environment (then you have to use python inside the virtual env to run the script). Or even easier, but not recommended: you could have installed all dependencies of requirements.txt with pip on the user level.
No clear understanding of how python and virtual environments work together can in fact cause a lot of problems.

**Comment by PWhiddy** [comment]
Hi! Thanks all for looking into this. Hope to add instructions for running on windows soon! (Or if anyone has done this already please feel free to open a PR adding windows instructions)

**Comment by MichaelJenningsAI** [comment]
I had to download ffmpeg.exe and put it in the baselines folder to make it run it windows. Otherwise pretty straight forward.

**Comment by setomage** [comment]
Current issue I'm having:

Traceback (most recent call last):
  File "C:\Users\Vince\Downloads\PokemonRedExperiments-master\baselines\run_baseline_parallel.py", line 4, in <module>
    from red_gym_env import RedGymEnv
  File "C:\Users\Vince\Downloads\PokemonRedExperiments-master\baselines\red_gym_env.py", line 10, in <module>
    from einops import rearrange
ModuleNotFoundError: No module named 'einops'

**Comment by Sorky96** [comment]
You didn't install dependencies successfully.
Propably you had same issue as me, try installing c++ 14+

**Comment by setomage** [comment]
Thanks everyone for the help! I was able to get everything running. The missing sauce was what @digitaldreamer7 pointed out.

**Comment by setomage** [comment]
Now time to let the server run, and train my little AI to be the best.  ^_~
