### ISSUE TITLE
How to change GPU

### ISSUE THREAD

**Issue by jonthers** [PWhiddy/PokemonRedExperiments#165]
Hi, I have two GPUs: the core GPU (GPU 0) and a dedicated NVIDIA (GPU 1). I am seeing in the Windows task manager that runs in this graph which I feel is inefficient. How could I change it?

**Comment by PWhiddy** [comment]
pytorch can only use an nvidia gpu. If you have a nvidia gpu available and cuda installed, stable baselines will automatically use it. Note that even if your GPU is being used, it won't show a particularly high utilization because running the gameboy emulator is also a bottleneck for this RL training.

**Comment by jonthers** [comment]
![Screenshot (592)](https://github.com/PWhiddy/PokemonRedExperiments/assets/33113577/1f46e64c-3991-44e3-8d90-9cd604743cfa)
![Screenshot (591)](https://github.com/PWhiddy/PokemonRedExperiments/assets/33113577/b380c826-05c6-4925-9f03-5db3634d825c)

**Comment by jonthers** [comment]
I am running the script normally and this is the use I have in the graphs. The 128MB vram Xe Graphics Intel is being used every time I run the script. and NVIDIA is at 0 in all its sectors

**Comment by PWhiddy** [comment]
If you run python and do
```
import torch
torch.cuda.is_available()
```
You can see if your pytorch installation has your cuda gpu available. If this shows false, try following instructions to install pytorch with cuda support on windows. 
https://pytorch.org/get-started/locally/
Once the above commands^ come back with "true", then you can try running the training again.

**Comment by jonthers** [comment]
Perfect! Thanks!
![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/33113577/8c2f2c24-8119-4e65-bdc6-37bd9a2962f7)
