### ISSUE TITLE
i got an error when i tried to install requirements.txt 

### ISSUE THREAD

**Issue by lplegend45678** [PWhiddy/PokemonRedExperiments#173]
× Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup C:\Users\maxim\AppData\Local\Temp\pip-install-9nzkuro0\contourpy_aaca6bc26f4d4711a12785eb123ce07a C:\Users\maxim\AppData\Local\Temp\pip-install-9nzkuro0\contourpy_aaca6bc26f4d4711a12785eb123ce07a\.mesonpy-e4wmxdff -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\maxim\AppData\Local\Temp\pip-install-9nzkuro0\contourpy_aaca6bc26f4d4711a12785eb123ce07a\.mesonpy-e4wmxdff\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: C:\Users\maxim\AppData\Local\Temp\pip-install-9nzkuro0\contourpy_aaca6bc26f4d4711a12785eb123ce07a
      Build dir: C:\Users\maxim\AppData\Local\Temp\pip-install-9nzkuro0\contourpy_aaca6bc26f4d4711a12785eb123ce07a\.mesonpy-e4wmxdff
      Build type: native build
      Project version: 1.1.0
     
      ..\meson.build:1:0: ERROR: Could not parse vswhere.exe output
     
      A full log can be found at C:\Users\maxim\AppData\Local\Temp\pip-install-9nzkuro0\contourpy_aaca6bc26f4d4711a12785eb123ce07a\.mesonpy-e4wmxdff\meson-logs\meson-log.txt
      [end of output]

error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by PWhiddy** [comment]
Hello!
I think what's missing is you need the microsoft c++ build tools.
 
You can refer to the windows setup guide for full instructions:  
https://github.com/PWhiddy/PokemonRedExperiments/blob/master/windows-setup-guide.md
