### ISSUE TITLE
Visualizations Troubles

### ISSUE THREAD

**Issue by alexkrolak** [PWhiddy/PokemonRedExperiments#19]
I'm unable to get the visualizations to work after a few attempts to debug. I'm able to successfully open up the Jupyter Notebook and run the cells, but my first issue appears when I get to cell 7 or so:
"plt.figure(figsize = (32, 32))
plt.imshow(get_latest_grid('baselines/session_24b49e0b'))"

I've tried changing the session file name and I get the same sorts of errors like so. Has anyone seen this before/know how to get the visualizations up and running? I'm brand new to all of this.

Errors output in Jupyter Notebook when running the two lines in cell 7:

EinopsError                               Traceback (most recent call last)
File ~\anaconda3\Lib\site-packages\einops\einops.py:412, in reduce(tensor, pattern, reduction, **axes_lengths)
    411     recipe = _prepare_transformation_recipe(pattern, reduction, axes_lengths=hashable_axes_lengths)
--> 412     return _apply_recipe(recipe, tensor, reduction_type=reduction)
    413 except EinopsError as e:

File ~\anaconda3\Lib\site-packages\einops\einops.py:235, in _apply_recipe(recipe, tensor, reduction_type)
    233 backend = get_backend(tensor)
    234 init_shapes, reduced_axes, axes_reordering, added_axes, final_shapes = \
--> 235     _reconstruct_from_shape(recipe, backend.shape(tensor))
    236 tensor = backend.reshape(tensor, init_shapes)

File ~\anaconda3\Lib\site-packages\einops\einops.py:200, in _reconstruct_from_shape_uncached(self, shape)
    199 if isinstance(length, int) and isinstance(known_product, int) and length % known_product != 0:
--> 200     raise EinopsError("Shape mismatch, can't divide axis of length {} in chunks of {}".format(
    201         length, known_product))
    203 unknown_axis = unknown_axes[0]

EinopsError: Shape mismatch, can't divide axis of length 6 in chunks of 4

During handling of the above exception, another exception occurred:

EinopsError                               Traceback (most recent call last)
Cell In[8], line 2
      1 plt.figure(figsize = (32, 32))
----> 2 plt.imshow(get_latest_grid('baselines/session_24b49e0b'))

Cell In[5], line 3, in get_latest_grid(pth)
      1 def get_latest_grid(pth):
      2     imgs = np.array([np.array(Image.open(p)) for p in Path(pth).glob('curframe*.jpeg')])
----> 3     grid = rearrange(imgs, '(h2 w2) h w c -> (h2 h) (w2 w) c', w2=4)
      4     return grid

File ~\anaconda3\Lib\site-packages\einops\einops.py:483, in rearrange(tensor, pattern, **axes_lengths)
    481         raise TypeError("Rearrange can't be applied to an empty list")
    482     tensor = get_backend(tensor[0]).stack_on_zeroth_dimension(tensor)
--> 483 return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)

File ~\anaconda3\Lib\site-packages\einops\einops.py:420, in reduce(tensor, pattern, reduction, **axes_lengths)
    418     message += '\n Input is list. '
    419 message += 'Additional info: {}.'.format(axes_lengths)
--> 420 raise EinopsError(message + '\n {}'.format(e))

EinopsError:  Error while processing rearrange-reduction pattern "(h2 w2) h w c -> (h2 h) (w2 w) c".
 Input tensor shape: (6, 144, 160, 3). Additional info: {'w2': 4}.
 Shape mismatch, can't divide axis of length 6 in chunks of 4

<Figure size 3200x3200 with 0 Axes>

**Comment by rparrett** [comment]
I came here to open my own issue, but I'll just drop this here: 

Here are a few things I encountered while trying to do visualization.

- there was a line like `f tqdm` in the imports. This is probably supposed to be `from tqdm import tqdm`?
- as you mentioned, the session name is hardcoded in many places, so you need to replace all of those.
- if you have customized `num_cpu`, look for places where `44` is hardcoded in the visualization and update those
- there is also a `rearrange` call that assumes that `num_cpu` is divisible by 4. the 4 there needs to be changed to a divisor of `num_cpu`

After fixing those up, things would be mostly working.

**Comment by Suneeth13** [comment]
try this and lemme' know if works:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as mplcm
import matplotlib.colors as colors
from einops import rearrange
from PIL import Image
from pathlib import Path
from sklearn import linear_model

from tqdm import tqdm  # Import tqdm here

def load_run_data(run_path):
    run_lists = []
    for p in Path(run_path).glob('all_runs_*.json'):
        with open(p, 'r') as f:
            run_lists.append(json.load(f))
    all_runs = [val for tup in zip(*run_lists) for val in tup]
    print(f'runs loaded: {len(all_runs)}')
    return all_runs

def plot_runs(all_runs, use_keys=None, plot_fit=False, plot_line=False, start=0, group_runs=1, agg_func=np.mean):
    all_runs = all_runs[start:]
    x = np.arange(len(all_runs) // group_runs)
    
    def add_plot(y, name, alpha, size, plot_line, plot_fit):
        plt.scatter(x, y, alpha=alpha, s=size, label=name)
        if plot_line:
            plt.plot(x, y, alpha=alpha, label=name)
        if plot_fit:
            regr = linear_model.LinearRegression()
            regr.fit(x.reshape(-1, 1), y.reshape(-1, 1))
            lin_y = regr.predict(x.reshape(-1, 1))
            plt.plot(x, lin_y, linewidth=3)
    
    metrics = {m: [run[m] for run in all_runs] for m in all_runs[0].keys()}
    metrics['total'] = [sum([v for _, v in run.items()]) for run in all_runs]
    
    if group_runs:
        for m, dat in metrics.items():
            metrics[m] = agg_func(np.array(dat).reshape(-1, group_runs), 1)
    
    available_keys = metrics.keys()
    print(f'available metrics: {list(available_keys)}')
    
    if use_keys is None:
        use_keys = available_keys
    
    NUM_COLORS = len(use_keys)
    cm = plt.get_cmap('Dark2')
    cNorm = colors.Normalize(vmin=0, vmax=NUM_COLORS - 1)
    scalarMap = mplcm.ScalarMappable(norm=cNorm, cmap=cm)
    fig = plt.figure(figsize=(12, 8))
    
    ax = fig.add_subplot(111)
    ax.set_prop_cycle(color=[scalarMap.to_rgba(i) for i in range(NUM_COLORS)]
    
    for i, m in enumerate(use_keys):
        add_plot(np.array(metrics[m]), m, 1.0, 3.0, plot_line, plot_fit)

    plt.title('Reward over runs PPO')
    plt.legend(bbox_to_anchor=(1.04, 0.5), loc="center left", borderaxespad=0)
    plt.show()

def get_latest_grid(pth):
    imgs = np.array([np.array(Image.open(p)) for p in Path(pth).glob('curframe*.jpeg')])
    grid = rearrange(imgs, '(h2 w2) h w c -> (h2 h) (w2 w) c', w2=4)
    return grid

def histo_plot(axis, stat, dat_chunks, version, compare_count):
    test_dat = np.array([run[stat] for run in dat_chunks[version]])
    n, bins, patches = axis.hist(test_dat, 10, density=False, facecolor="orange", alpha=0.95)
    
    for i in range(compare_count):
        comp_version = max(version - 1 - i, 0)
        compare_dat = np.array([run[stat] for run in dat_chunks[comp_version]])
        n, bins, patches = axis.hist(compare_dat, 10, density=False, facecolor="grey", alpha=0.2 * 0.25**i)
    
    axis.set(xlabel=f"{stat}")

def plot_all(dat_chunks, version, compare_count):
    fig, axs = plt.subplots(2, 4, figsize=(16, 9), dpi=120)
    fig.suptitle(f"Version {version} Rewards")
    for stat, ax in zip(dat_chunks[0][0].keys(), axs.flatten()):
        histo_plot(ax, stat, dat_chunks, version, compare_count)
    return fig

# Debugging your code:
load_run_data('baselines/session_4da05e87_main_full')  # Check if data loads correctly
plot_runs(load_run_data('baselines/session_4da05e87_main_full'), use_keys=None)  # Debug plot_runs
plot_all(chunks(full_dat, 44), 10, 5)  # Debug plot_all

**Comment by alexkrolak** [comment]
> * rearrange

This helped a ton!
I'm just playing around with things and only have a single 6 core CPU, so this solved a ton of potential problems all at once! I can see some pretty pictures now!

**Comment by PWhiddy** [comment]
Hi yes the code arranges the screens into a grid and you'll get that error if your number of screens/games isn't divisible by the grid dimension. Glad you were able to get it working :) 
Code could probably use an automatic check though.

**Comment by Suneeth13** [comment]
Glad that it works

**Comment by PWhiddy** [comment]
It is not unusual for the performance to decrease or stop working, the optimization can be quite fragile. You're using much less environments than the original version, so you can try tweaking parameters to get it learning better. You could try lowing the discount factor (gamma) a little, or changing episode length, or try to start by disabling all rewards except for exploration. Might take some experimentation but eventually you should see the reward start to climb! 

Also documentation for PPO in stable baselines:
https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html
