### ISSUE TITLE
NameError: name 'file_name' is not defined

### ISSUE THREAD

**Issue by handofiron** [PWhiddy/PokemonRedExperiments#194]
I know this repo has not seen much love but I'd love to continue work on this and get it running in docker so it can be left to run on my homelab for a few years or something but I'm getting this error when trying to run the v2

(venv) admin@gungnir:~/PokemonRedExperiments/v2$ python3 run_pretrained_interactive.py
UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.2

loading checkpoint
Traceback (most recent call last):
  File "/home/jay_admin/PokemonRedExperiments/v2/run_pretrained_interactive.py", line 70, in <module>
    model = PPO.load(file_name, env=env, custom_objects={'lr_schedule': 0, 'clip_range': 0})
                     ^^^^^^^^^
NameError: name 'file_name' is not defined

**Comment by PWhiddy** [comment]
I've been giving it as much love as I'm able :)
There isn't a checkpoint in the repo yet for v2. I might have the chance to upload one in the future, or perhaps someone else can contribute one. For now you'll have to train it yourself if you want a pretrained checkpoint!

**Comment by handofiron** [comment]
Thanks for the reply buddy I didn't think I would get one. are you not using the V2 scripts in your youtube video then? Super impressive stuff by the way.

I will have a go at it buddy was just curious on peoples involvement before hand.

**Comment by PWhiddy** [comment]
v2 is newer than the video.

also feel free to check out the discord server!

**Comment by handofiron** [comment]
I've joined the discord my man, just running the baseline_v2 now hopefully have this working from a docker container like i say.
