### ISSUE TITLE
Nvidia cuBLAS cu12

### ISSUE THREAD

**Issue by amathew4538** [PWhiddy/PokemonRedExperiments#195]
I got this error message while running the pip. Will this be a problem, and, if so, how do I fix it? I'm running on Visual Studio Code - Insiders on an 8Gb RAM M2 macOS Sonoma 14.7.1 MacBook Air if that helps. The setup has worked up till this one.

ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu12==12.4.5.8 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-cublas-cu12==12.4.5.8

**Comment by PWhiddy** [comment]
Hey!
If you're on a mac you won't be able to use cuda, but if you just individually install pytorch with `pip install torch` you should get a working version, likely one can use the apple gpu via MPS at least.

**Comment by amathew4538** [comment]
Ok, I did that, but now I'm getting an error in which 7 of the imports don't work. Also, I would recommend telling people that you can do it through visual studio and get conda and pip to work by using `~/anaconda3/bin/activate` then `conda init zsh` to get conda to work, and (on Mac) `python3 -m pip install {package_here}`.

**Comment by amathew4538** [comment]
Here's the requirements.txt pip: `python3 -m pip install -r ~/path-to-PokemonRedExperiments-folder/PokemonRedExperements/requirements.txt`

**Comment by PWhiddy** [comment]
If you want to submit a PR with a frozen `requirements.txt` that works on macos, I'd appreciate it!

**Comment by amathew4538** [comment]
I am having a problem where stable baselines wont import. any ideas?
