### ISSUE TITLE
Question about baseline_fast_v2.py

### ISSUE THREAD

**Issue by amathew4538** [PWhiddy/PokemonRedExperiments#197]
Does baseline_fast_v2.py automatically use what the ai learned from the previous run, or do I need to configure that. Also, is there a way to run it constantly?

**Comment by PWhiddy** [comment]
The training script by default will periodically save model checkpoints zip files.
you can continue training again from a checkpoint by putting the path of a checkpoint file here:

https://github.com/PWhiddy/PokemonRedExperiments/blob/dcd18e676e377bf29be602b4a2bed71b28f89b91/v2/baseline_fast_v2.py#L77

I'm not sure what you mean by "run it constantly".

**Comment by amathew4538** [comment]
Sorry, I didn't see this earlier. 1st, does the zip save to the runs folder, or where is it? 2nd, can the ai train, and once it has finished, train again directly after? I've tried a while true loop, but that crashed it. 3rd, why am I getting a KeyError: 'print_rewards'?
