### ISSUE TITLE
v2 doesn't include base run for run_pretrained_interactive

### ISSUE THREAD

**Issue by lucas-wb** [PWhiddy/PokemonRedExperiments#199]
The run_pretrained_interactive.py script in /v2/ errors as pulled. 
file_name is not set unless a run exists, and no runs are in the repo. 

This run is in baselines, but it doesn't work for v2 when put in the /v2/runs/.
/PokemonRedExperiments/baselines/session_4da05e87_main_good/poke_439746560_steps.zip

Is there a new v2 run that was accidentally excluded or is there some other way to generate a run?

```python
#env_checker.check_env(env)
    most_recent_checkpoint = get_most_recent_checkpoint()
    if most_recent_checkpoint is not None:
        file_name = most_recent_checkpoint
    
    # could optionally manually specify a checkpoint here
    # file_name = "runs/poke_124800_steps.zip"
    
    print('\nloading checkpoint')
    model = PPO.load(file_name, env=env, custom_objects={'lr_schedule': 0, 'clip_range': 0})
```

**Comment by PWhiddy** [comment]
Hi!
This is a known issue (#194)
I just started a training run to create a checkpoint! Hopefully will be done in the next couple days and I'll add it.

**Comment by PWhiddy** [comment]
you can also create your own checkpoints by training the model yourself!

**Comment by lucas-wb** [comment]
Oh, Sorry about that, I didn't see that one! Thank you for all your work here
