### ISSUE TITLE
Add Pokémon Red hash to readme for ROM validity

### ISSUE THREAD

**Issue by sctjkc01** [PWhiddy/PokemonRedExperiments#4]
I would suggest adding an expected hash for the copy of the game that you're expecting the AI to run; something like the output of `md5sum PokemonRed.gb`.  That way, it'd be far easier to validate that this is the _correct_ ROM to be running in this environment, rather than one that might be slightly tweaked, and thus might have memory values in unexpected locations.  Simply saying it's "about 1MB" unfortunately isn't that helpful.

**Comment by PWhiddy** [comment]
Great idea! added.
