### ISSUE TITLE
Problem installing GitHub packages: "Cannot find command 'git' - do you have 'git' installed and in your PATH?"

### ISSUE THREAD

**Issue by Stardemon24** [PWhiddy/PokemonRedExperiments#55]
C:\Users\Erick\Downloads\PokemonRedExperiments-master\PokemonRedExperiments-master\baselines>pip install -r requirements.txt
Collecting mediapy@ git+https://github.com/PWhiddy/mediapy.git@45101800d4f6adeffe814cad93de1db67c1bd614 (from -r requirements.txt (line 94))
  Cloning https://github.com/PWhiddy/mediapy.git (to revision 45101800d4f6adeffe814cad93de1db67c1bd614) to c:\users\erick\appdata\local\temp\pip-install-n111e2vg\mediapy_764d51226f3847c0aa82f633e4c029ce
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

I have already checked that 'git' is in the PATH and I've also uninstalled git and reinstalled it but it's not working

**Comment by PWhiddy** [comment]
so if you type `git` in the same command line and hit enter you don't see the same error?
