### ISSUE TITLE
VisualizeProgress with errors

### ISSUE THREAD

**Issue by JGsouzaa** [PWhiddy/PokemonRedExperiments#64]
There are some errors messages on jupyter notebook that I think could be fixed (maybe some update of jupyter that crashed the old notebook), don't know if it matters to much for the purpourse of the project...

![Screenshot_20231017-164715.png](https://github.com/PWhiddy/PokemonRedExperiments/assets/99425339/2df51e5e-0b1b-40eb-9848-59bc4d55a4fa)

![Screenshot_20231017-164725.png](https://github.com/PWhiddy/PokemonRedExperiments/assets/99425339/136088c2-e4ab-4f73-b2fe-2ab1fd110a31)

**Comment by PWhiddy** [comment]
@JGsouzaa were you able to get it working?

**Comment by JGsouzaa** [comment]
Yes thanks
