### ISSUE TITLE
Unable to install pyboy

### ISSUE THREAD

**Issue by fau1095** [PWhiddy/PokemonRedExperiments#66]
Has anyone run into this issue? Any help will be appreciated:
![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/112910053/0c117101-8ee0-4aab-bdcb-f47b31851894)

```
(pokey) fabriziomendez@Fabrizios-MacBook-Pro baselines % python3.10 -m pip install pyboy     
Collecting pyboy
  Using cached pyboy-1.5.6.tar.gz (5.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      <string>:40: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

```

**Comment by Goulustis** [comment]
Probably some dependency issue, Try conda:

conda install pyboy

**Comment by fau1095** [comment]
> Probably some dependency issue, Try conda:
> 
> conda install pyboy

Good call but still getting errors:

```
(pokey) fabriziomendez@Fabrizios-MacBook-Pro baselines % conda install pyboy
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyboy

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by Goulustis** [comment]
Huh, conda doesn't have pyboy as package.

The main problem is your python3.10 cannot find pip.
Try:
python -m pip install pyboy

intead

**Comment by sonnees** [comment]
i love your project

**Comment by fau1095** [comment]
Update: I was able to resolve the issue, not sure how but I managed to reinstall lots of the dependencies. Currently able to run it only on python3.11 for some reason, but I don't care since it works :) 

![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/112910053/8478cd3b-b47b-4282-b202-78270f873d62)

**Comment by NGallop** [comment]
In case anyone else comes looking, I found the same problem. I removed pyboy from the requirements.txt and pip installed the rest. I then used pip install pyboy==1.5.6 to install it manually. This still ran into an error about not being able to find ffmpeg - which I couldn't find in the requirements doc so this might be something to do with pyboy being installed this way. I ran pip install ffmpeg-python and pip install ffmpeg to no avail, but conda install ffmpeg installed loads of additional pakages and now it's up and running!

**Comment by Baekalfen** [comment]
PyBoy has been updated to fix the problem in the first post. As the warning says, PyBoy was using a deprecated feature, but that is fixed now. There's no reason to install PyBoy 1.5.6 specifically. Rather do: `pip install 'pyboy>=1.6.0'`
