### ISSUE TITLE
run_baseline.py headless

### ISSUE THREAD

**Issue by havedill** [PWhiddy/PokemonRedExperiments#71]
For fun i'm messing around with some of the reward variables. However, when i run run_baseline.py with headless = False, it does not show the emulator UI

It works perfectly fine when i run the interactive.py. Am i missing something to make it appear elsewhere?

**Comment by havedill** [comment]
Nevermind I found i had to put it into the args variable, not env_config

args = get_args('run_baseline.py', ep_length=run_steps, sess_path=sess_path, **headless=False**)

**Comment by PWhiddy** [comment]
Editing it in the run_baseline file itself didn't work?

**Comment by havedill** [comment]
No it did, i just didn't realize  headless was an argument to get_args, I saw it in env_config and assumed that was the only placei t was needed
