### ISSUE TITLE
Don't get any video output

### ISSUE THREAD

**Issue by JSW88** [PWhiddy/PokemonRedExperiments#73]
It seems to be running for me, although I needed to install some of the dependencies manually. I don't get a video screen, just text with updates on steps etc. 

Not sure if this is because I'm using WSL, but I have got ffmpeg installed and I'm using Python3.

![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/6970389/09f22726-5f16-4584-bf49-e699a6b1933d)

I'm using fish as my shell there, but I did try it with bash too.

**Comment by PWhiddy** [comment]
Hi!
Are you able to open other GUI applications successfully from WSL? 
I think it should work out of the box with wsl2:
https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

**Comment by JSW88** [comment]
Thanks for the incredibly fast reply! This will probably be it, I'm on WSL 1, so just upgrading to 2 now.

**Comment by JSW88** [comment]
So I'm now on WSL2 and the Pyboy window opens. Unfortunately, it crashes shortly afterwards.

![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/6970389/71ba9c67-8f63-4995-aa68-85a24ba717d8)

**Comment by PWhiddy** [comment]
Do other GUI applications work fine in your WSL2?
