### ISSUE TITLE
Migrate metrics tracking to tensorboard

### ISSUE THREAD

**Issue by PWhiddy** [PWhiddy/PokemonRedExperiments#78]
Current notebook setup is very shabby. Reward data and model stats, and even gameplay clips can all be automatically be sent to tensorboard for easy visualization.

**Comment by jsuarez5341** [comment]
Open to Wandb? Check other post, I can take care of it if I know what game stats to log

**Comment by PWhiddy** [comment]
tensorboard + wandb added
