### ISSUE TITLE
SyntaxError when running python run_pretrained_interactive.py

### ISSUE THREAD

**Issue by GhoulWorlde** [PWhiddy/PokemonRedExperiments#8]
The aforementioned command leads to the following output 

  File "run_pretrained_interactive.py", line 29
    sess_path = f'session_{str(uuid.uuid4())[:8]}'

SyntaxError: invalid syntax

**Comment by PWhiddy** [comment]
Are you using a recent version of python? fstrings need >=3.6. I've only tested this project with 3.10

**Comment by GhoulWorlde** [comment]
Ah I see. Running it as python3 run_pretrained_interactive.py worked
