### ISSUE TITLE
No "start" button to interact while ai is playing?

### ISSUE THREAD

**Issue by manueldanze** [PWhiddy/PokemonRedExperiments#89]
I noticed that there is no corresponding key for the start button.. or do i miss something? can't find the key assignments for interaction with a running game.

very impressive work :)

**Comment by PWhiddy** [comment]
Hey!

## Short answer:
Start Button -> Return key

## Long answer:

If you start the emulator like this:
```python -m pyboy <game_rom_path_here>.gb```

It will print out the controls. This just doesn't happen by default in the script.

Anyway here's what it looks like:

| Keyboard key | GameBoy equivalant |
| ---          | ---                |
| Up           | Up                 |
| Down         | Down               |
| Left         | Left               |
| Right        | Right              |
| A            | A                  |
| S            | B                  |
| Return       | Start              |
| Backspace    | Select             |

The other controls for the emulator:

| Keyboard key | Emulator function       |
| ---          | ---                     |
| F11          | Toggle fullscreen       |
| Escape       | Quit                    |
| D            | Debug                   |
| Space        | Unlimited FPS           |
| Z            | Save state              |
| X            | Load state              |
| I            | Toggle screen recording |
| O            | Save screenshot         |
| ,            | Rewind backwards        |
| .            | Rewind forward          |
| J            | Memory Window + 0x100   |
| K            | Memory Window - 0x100   |
| Shift + J    | Memory Window + 0x1000  |
| Shift + K    | Memory Window - 0x1000  |
