### ISSUE TITLE
I am experiencing the following error. pip install -r requirements.txt

### ISSUE THREAD

**Issue by yigitalpkorpe** [PWhiddy/PokemonRedExperiments#90]
I am getting the following error. trying with python 3.10
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by PWhiddy** [comment]
Hi! I think think some of the error message there is cut off?

**Comment by yigitalpkorpe** [comment]
Hi! I could not know how prior I should go 
```
  [33/47] Cythonizing pyboy/plugins/disable_input.py
      [40/47] Cythonizing pyboy/plugins/screen_recorder.py
      [46/47] Cythonizing pyboy/pyboy.py
          ext_modules = cythonize(
        File "/private/var/folders/zh/kg3x76nn1yb83gr4gfvf72r40000gn/T/pip-install-1ujwyhqk/pyboy_699bdef694ae4025ba9eb01c1af31541/.eggs/Cython-3.0.4-py3.10-macosx-10.9-x86_64.egg/Cython/Build/Dependencies.py", line 1145, in cythonize
          result.get(99999)  # seconds
        File "/Users/yigitalpkorpe/miniconda3/envs/pokey/lib/python3.10/multiprocessing/pool.py", line 774, in get
          raise self._value
      Cython.Compiler.Errors.CompileError: pyboy/core/ram.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by yigitalpkorpe** [comment]
I saw someone yesterday who encountered the same error and fixed it.
https://github.com/PWhiddy/PokemonRedExperiments/issues/66#issuecomment-1772979336

**Comment by Baekalfen** [comment]
I just want to point out, that's not the actual fix. It was because of a bug in Cython, which PyBoy has a workaround for: https://github.com/cython/cython/issues/5771#event-10732931274
