### ISSUE TITLE
Pokemon Violet / Scarlet compatibility

### ISSUE THREAD

**Issue by camilopq97** [PWhiddy/PokemonRedExperiments#91]
When will you have compatibility with Switch's Violet / Scarlet??
Thanks man

**Comment by dukemagus** [comment]
Out of scope. This repo is for the Pokémon red experiment.

**Comment by setomage** [comment]
That would have to be a whole new program, and would need way more rss

**Comment by MIKAH-PIKA** [comment]
the code for it all is made for pokemon red a gameboy game not a Switch

**Comment by binary3141** [comment]
maybe use Violet / Scarlet version gba rom

**Comment by PWhiddy** [comment]
The reason this is difficult is that it would require an entirely different emulator, that has an API as nice as pyboy
