### ISSUE TITLE
No Sound on Script?

### ISSUE THREAD

**Issue by ZoDIkarus** [PWhiddy/PokemonRedExperiments#92]
It Runs like a Charm but i have no sound when i let the pretrained Script running.

And 1 more question how can i run more then 10 Runs Visualises i would like to let 10 Emulations go on and watch them :D gj for the nice work

**Comment by Baekalfen** [comment]
In `baselines/reg_gym_env.py` replace line 100 onwards with this:
```python
        self.pyboy = PyBoy(
                config['gb_path'],
                debugging=False,
                disable_input=False,
                window_type=head,
                hide_window='--quiet' in sys.argv,
                sound=True, # Turn on sound
            )

        self.screen = self.pyboy.botsupport_manager().screen()

        if not config['headless']:
            self.pyboy.set_emulation_speed(1) # set emulation speed to 1, so you can hear it.
```

https://github.com/PWhiddy/PokemonRedExperiments/blob/adede35f3d120127f73c05678c445b76263a81d5/baselines/red_gym_env.py#L100C22-L100C22
