### ISSUE TITLE
Issue in the requirements specifically "hnswlib"

### ISSUE THREAD

**Issue by darkn38** [PWhiddy/PokemonRedExperiments#93]
Building wheels for collected packages: hnswlib
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects

I already installed the required VSBuild Tools v17.7.5 which is already higher than the required v14.0 already did restart hoping it would solve the issue but yeah im still stuck.. already used chatgpt in which the suggestion was the same about installing the VSBuild Tools..

**Comment by RussellMaggs** [comment]
I don't recall if it was the exact same error I faced when I setup my computer but it was certainly a similar error.

I followed the instructions of the top comment [here](https://stackoverflow.com/questions/73969269/error-could-not-build-wheels-for-hnswlib-which-is-required-to-install-pyprojec)

and it resolved the issue for me.

**Comment by darkn38** [comment]
still having the same error

**Comment by PWhiddy** [comment]
So you already installed VSBuild tools? Maybe it not added to your Path somehow or isn't visible from your command line? 
Is there another way to verify your Microsoft Visual C++ is working perhaps?

Another possible workaround is to use WSL2.

**Comment by darkn38** [comment]
![Screenshot 2023-10-24 202407](https://github.com/PWhiddy/PokemonRedExperiments/assets/114572221/0af94c0a-4b1c-47aa-9e65-fd00a830ae93)
@PWhiddy its already working based on that i guess
