### ISSUE TITLE
I can help, DM me

### ISSUE THREAD

**Issue by jsuarez5341** [PWhiddy/PokemonRedExperiments#94]
Hi,

Awesome work! Have wanted Pokemon as an RL env for years. I dev pufferlib (pufferai.github.io), a library for aggregating RL environments and making them easier to work with. I've done an initial integration for your Pokemon Red Gym env and would like to help you with the project. I have a box capable of running experiments as well. My Discord is jsuarez5341, let's chat

**Comment by jsuarez5341** [comment]
Quick local run in Wandb. Getting around 50 steps/second/core.

https://wandb.ai/jsuarez/pufferlib/runs/2xsuovz7?workspace=user-jsuarez

<img width="801" alt="image" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/14065750/7496388e-b32b-45cf-bf37-af10dd3d35a3">

This is just a small local test, but once I can finish porting and run full scale, it contains some useful debug information that can help further optimize training. I have some questions about what info to log though ... What performance metrics should I grab at the end of the episode?

**Comment by jsuarez5341** [comment]
<img width="1197" alt="image" src="https://github.com/PWhiddy/PokemonRedExperiments/assets/14065750/74cb6a28-6a5a-4ebf-90d2-b477c3dd8ed1">

Got some stats, curves are flat though... possibly just because I'm running too small scale... still, this should be about what you wanted, right?

**Comment by jsuarez5341** [comment]
https://wandb.ai/jsuarez/pufferlib?workspace=user-jsuarez

Going to sleep. Got it running on my box, ~1000 steps per second on 22 cores. I guessed some hyperparameters to start. If this doesn't crash, it will run 40M frames in around 12-16 hours

**Comment by techmore** [comment]
This is pretty cool. I hope you are able to publish and share the code changes and metrics. This seems like a better solution to compare the metrics of the various trained models. 

Thank you for contributing.

**Comment by jsuarez5341** [comment]
everything is public. github/pufferai/pufferlib, 0.5-cleanup branch for now. Also coordinating dev at discord.gg/puffer. Once creator replies, hopefully I can help push everything into a standalone pokemon red pip package

**Comment by PWhiddy** [comment]
Thanks @jsuarez5341 this is awesome! 
By "standalone pokemon red pip package" you're talking about packaging the environment so that it's easy to pull into other RL libraries? 
I sent you twitter dm but also now am seeing your discord, will reach out there.
