### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by rousks** [PWhiddy/PokemonRedExperiments#97]
My issue is that there isn't a discord to discuss this project :(

**Comment by techmore** [comment]
https://discord.gg/axGZT8Nf

This seemed easy enough... not we need more people on it!

**Comment by jsuarez5341** [comment]
If the creator does not wish to maintain one, I am working on this over at discord.gg/puffer (library dedicated to making RL projects like this easy to work with)

**Comment by techmore** [comment]
At this time it's probably best to move to puffer to centralize some development. When pwhiddy is free we can transfer ownership on the current discord/PokemonRedExperiments server for his keeping.

**Comment by PWhiddy** [comment]
I'd be happy to have a discord if others are willing to help admin it! I can set one up in the next day or two. In the meantime we can collaborate in the puffer discord.

**Comment by luiscosio** [comment]
Heading to the Puffer discord then.

**Comment by PWhiddy** [comment]
Hey all! there's now a dedicated discord server here!  
http://discord.gg/RvadteZk4G
